# Generated by Django 3.2.5 on 2021-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
    ]
